export const CustomIds = {
  TICKET_PURCHASE: 'ticket:purchase',
  TICKET_SUPPORT: 'ticket:support',
  TICKET_INQUIRY: 'ticket:inquiry',
  TICKET_CLOSE: 'ticket:close',
  PRODUCT_SELECT: 'ticket:product-select',
  PRODUCT_REMOVE: 'admin:product-remove',
  PRODUCT_DELETE_ALL_CONFIRM: 'admin:product-delete-all-confirm',
  PRODUCT_DELETE_ALL_CANCEL: 'admin:product-delete-all-cancel',
  FEEDBACK_OPEN: 'feedback:open',
  MODAL_LICENSE: 'modal:license',
  MODAL_FEEDBACK: 'modal:feedback',
  MODMAIL_START: 'modmail:start',
  MODMAIL_CLOSE: 'modmail:close',
  KEY_SELECT: 'key:select',
  KEY_CANCEL_SELECT: 'key:cancel:select',
  KEY_ADD_MONTH: 'key:add_month',
  KEY_REMOVE_MONTH: 'key:remove_month',
  KEY_CONFIRM_CANCEL: 'key:confirm_cancel',
  KEY_CANCEL_ABORT: 'key:cancel_abort',
  KEY_ADJUST_MONTHS: 'key:adjust_months',
  MODAL_ADJUST_MONTHS: 'modal:adjust_months',
} as const;

export type TicketType = 'purchase' | 'support' | 'inquiry';
